using System.IO;
using System.Text;

namespace SteamVault.Services;

/// <summary>
/// Generates .lua configuration files for OpenSteamTool / SteamTools stplug-in.
/// 
/// Correct format (from OpenSteamTool / SteamTools docs):
///   addappid(APPID)                          -- register the game
///   addtoken(APPID, "ACCESS_TOKEN")          -- app access token (if available)
///   addappid(DEPOTID, 1, "DECRYPTION_KEY")   -- register depot decryption key under its own depot ID
///   setManifestid(DEPOTID, "MANIFEST_GID")   -- pin specific depot to a manifest (quoted GID)
///   setAppTicket("HEX_TICKET")               -- OpenSteamTool v1.4.7+: AppTicket for SteamStub-only games
///   setETicket("HEX_TICKET")                 -- OpenSteamTool v1.4.7+: ETicket hex string
///
/// Decryption keys are registered against the DEPOT ID (not the parent app ID).
/// Each depot gets its own key registration so OpenSteamTool can decrypt it.
/// </summary>
public class LuaGeneratorService
{
    /// <summary>
    /// Generate and save a .lua file for the given app and its depots.
    /// </summary>
    public string GenerateLuaFile(
        string appId,
        string gameName,
        List<DepotLuaEntry> depots,
        string luaOutputPath,
        string? appAccessToken = null,
        List<DlcLuaEntry>? dlcs = null,
        string? appTicket = null,
        string? eTicket = null,
        string? appDecryptionKey = null)
    {
        Directory.CreateDirectory(luaOutputPath);

        var sb = new StringBuilder();
        var addedIds = new HashSet<string>();

        sb.AppendLine($"-- {gameName}");
        sb.AppendLine($"-- AppID: {appId}");
        sb.AppendLine($"-- Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"-- Generated by SteamVault (https://github.com/Fluxerr/SteamVault)");
        sb.AppendLine();

        void AddAppId(string id, string? key = null)
        {
            var hasKey = !string.IsNullOrWhiteSpace(key);
            var line = hasKey ? $"addappid({id}, 1, \"{key}\")" : $"addappid({id})";
            
            // If we already added this exact line, skip it
            if (!addedIds.Add(line)) return;

            // If we are adding a version WITH a key, and we previously added one WITHOUT a key,
            // we should ideally replace it, but practically just emitting it is fine.
            // However, to prevent `addappid(123)` followed by `addappid(123)`, we can also track just the ID.
            if (!hasKey)
            {
                // Only add keyless if we haven't added ANY version of this ID
                var keyVersionExists = addedIds.Any(a => a.StartsWith($"addappid({id}, 1,"));
                if (keyVersionExists) return;
            }

            sb.AppendLine(line);
        }

        // 1. Register the game's AppID (with key if this AppID also serves as a depot)
        //    Key priority: explicit appDecryptionKey > matching depot key in depots list > none
        var appKey = appDecryptionKey;
        if (string.IsNullOrWhiteSpace(appKey))
        {
            var appDepot = depots.FirstOrDefault(d => d.DepotId == appId);
            appKey = appDepot?.DecryptionKey;
        }
        AddAppId(appId, appKey);

        // 2. Add access token if we have one
        if (!string.IsNullOrWhiteSpace(appAccessToken))
        {
            sb.AppendLine($"addtoken({appId}, \"{appAccessToken}\")");
        }

        // 2b. AppTicket (OpenSteamTool v1.4.7+) — used for SteamStub-only games
        if (!string.IsNullOrWhiteSpace(appTicket))
        {
            sb.AppendLine($"setAppTicket(\"{appTicket}\")");
        }

        // 2c. ETicket (OpenSteamTool v1.4.7+)
        if (!string.IsNullOrWhiteSpace(eTicket))
        {
            sb.AppendLine($"setETicket(\"{eTicket}\")");
        }

        sb.AppendLine();

        // 3. Register each depot's decryption key and manifest ID
        // Key registration uses the DEPOT ID — each depot gets its own key
        foreach (var depot in depots)
        {
            if (depot.DepotId != appId)
            {
                AddAppId(depot.DepotId, depot.DecryptionKey);
            }

            if (!string.IsNullOrWhiteSpace(depot.ManifestId))
            {
                sb.AppendLine($"setManifestid({depot.DepotId}, \"{depot.ManifestId}\")");
            }
            sb.AppendLine();
        }

        // 4. DLC entries
        if (dlcs != null && dlcs.Count > 0)
        {
            sb.AppendLine("-- ═══ DLC Entries ═══");
            sb.AppendLine();
            foreach (var dlc in dlcs)
            {
                sb.AppendLine($"-- DLC: {dlc.Name} (App ID: {dlc.AppId})");
                
                // Add the DLC app id itself (for entitlement)
                // We add it without a key first, unless it happens to be a depot with a key, which will override it.
                // Wait, our AddAppId logic says if we add keyless, it skips if a keyed version exists.
                // But what if we add keyless NOW, and a keyed version comes later? It will add both.
                // That's acceptable and matches the working lua behavior in some cases, but let's just emit it.
                AddAppId(dlc.AppId);

                // Register DLC depots
                foreach (var depot in dlc.Depots)
                {
                    AddAppId(depot.DepotId, depot.DecryptionKey);

                    if (!string.IsNullOrWhiteSpace(depot.ManifestId))
                    {
                        sb.AppendLine($"setManifestid({depot.DepotId}, \"{depot.ManifestId}\")");
                    }
                }
                sb.AppendLine();
            }
        }

        // Save with AppID as filename
        var fileName = $"{appId}.lua";
        var filePath = Path.Combine(luaOutputPath, fileName);
        
        // Use UTF8 without BOM, as some Lua parsers (like SteamTools) fail to read files with a Byte Order Mark
        File.WriteAllText(filePath, sb.ToString(), new UTF8Encoding(false));

        return filePath;
    }
}

public class DepotLuaEntry
{
    public string DepotId { get; set; } = "";
    public string? DecryptionKey { get; set; }
    public string? ManifestId { get; set; }
}

public class DlcLuaEntry
{
    public string AppId { get; set; } = "";
    public string Name { get; set; } = "";
    public List<DepotLuaEntry> Depots { get; set; } = new();
}