using SteamVault.Models;
using System.IO;
using System.Text.RegularExpressions;

namespace SteamVault.Services;

/// <summary>
/// Parses existing .lua files generated by SteamVault to extract game metadata, depot info, and manifest IDs.
/// </summary>
public class LuaParserService
{
    // Matches: addappid(12345)
    private static readonly Regex AddAppIdRegex = new(@"addappid\((\d+)\)", RegexOptions.Compiled);

    // Matches: addappid(123456, 0, "DECRYPTION_KEY") or addappid(123456, 1, "KEY")
    private static readonly Regex AddAppIdWithKeyRegex = new(@"addappid\((\d+),\s*\d+,\s*""([^""]*)""\)", RegexOptions.Compiled);

    // Matches: addtoken(12345, "TOKEN")
    private static readonly Regex AddTokenRegex = new(@"addtoken\((\d+),\s*""([^""]*)""\)", RegexOptions.Compiled);

    // Matches: setManifestid(123456, "MANIFEST_GID")
    private static readonly Regex SetManifestIdRegex = new(@"setManifestid\((\d+),\s*""([^""]*)""\)", RegexOptions.Compiled);

    /// <summary>
    /// Scans the given folder for .lua files and returns a list of parsed LibraryEntry objects.
    /// </summary>
    public List<LibraryEntry> ScanLuaFolder(string luaOutputPath)
    {
        var entries = new List<LibraryEntry>();

        if (string.IsNullOrWhiteSpace(luaOutputPath) || !Directory.Exists(luaOutputPath))
            return entries;

        var luaFiles = Directory.GetFiles(luaOutputPath, "*.lua");
        foreach (var filePath in luaFiles)
        {
            try
            {
                var entry = ParseLuaFile(filePath);
                if (entry != null)
                {
                    entry.LuaFilePath = filePath;
                    entry.LastUpdated = File.GetLastWriteTime(filePath);
                    entries.Add(entry);
                }
            }
            catch
            {
                // Skip files that fail to parse
            }
        }

        return entries;
    }

    /// <summary>
    /// Parses a single .lua file and extracts all relevant information.
    /// </summary>
    public LibraryEntry? ParseLuaFile(string filePath)
    {
        if (!File.Exists(filePath)) return null;

        var content = File.ReadAllText(filePath);
        var entry = new LibraryEntry();

        // Extract game name from comment: -- GameName
        var nameMatch = Regex.Match(content, @"^--\s*(.+)$", RegexOptions.Multiline);
        if (nameMatch.Success)
        {
            var potentialName = nameMatch.Groups[1].Value.Trim();
            if (!potentialName.StartsWith("AppID:") && !potentialName.StartsWith("Generated:"))
            {
                entry.Name = potentialName;
            }
        }

        // Extract AppID from comment: -- AppID: 12345 or filename
        var appIdMatch = Regex.Match(content, @"--\s*AppID:\s*(\d+)");
        if (appIdMatch.Success)
        {
            entry.AppId = appIdMatch.Groups[1].Value;
        }
        else
        {
            // Fallback to filename
            entry.AppId = Path.GetFileNameWithoutExtension(filePath);
        }

        // Extract all addappid registrations (with and without keys)
        var depots = new Dictionary<string, LibraryDepotInfo>();

        // addappid with key: addappid(DEPOTID, 0, "KEY")
        foreach (Match m in AddAppIdWithKeyRegex.Matches(content))
        {
            var depotId = m.Groups[1].Value;
            var key = m.Groups[2].Value;
            if (!depots.ContainsKey(depotId))
                depots[depotId] = new LibraryDepotInfo { DepotId = depotId };
            depots[depotId].DecryptionKey = key;
        }

        // plain addappid without key
        foreach (Match m in AddAppIdRegex.Matches(content))
        {
            var depotId = m.Groups[1].Value;
            // Only add if not already captured by the keyed version as a keyed version
            // Actually we need to merge: the keyed version already sets DepotId, so check if exists
            if (!depots.ContainsKey(depotId))
                depots[depotId] = new LibraryDepotInfo { DepotId = depotId };
            // Don't overwrite an existing key with null
        }

        // Extract manifest IDs: setManifestid(DEPOTID, "MANIFEST_GID")
        foreach (Match m in SetManifestIdRegex.Matches(content))
        {
            var depotId = m.Groups[1].Value;
            var manifestId = m.Groups[2].Value;
            if (!depots.ContainsKey(depotId))
                depots[depotId] = new LibraryDepotInfo { DepotId = depotId };
            depots[depotId].ManifestId = manifestId;
        }

        // Include all depots found in the Lua file
        entry.Depots = new System.Collections.ObjectModel.ObservableCollection<LibraryDepotInfo>(
            depots.Values);

        return entry;
    }

    /// <summary>
    /// Extracts all depot-to-manifest mappings from a lua file content string.
    /// Returns dictionary of depotId -> manifestId.
    /// </summary>
    public Dictionary<string, string> GetManifestMappings(string filePath)
    {
        var mappings = new Dictionary<string, string>();
        if (!File.Exists(filePath)) return mappings;

        var content = File.ReadAllText(filePath);
        foreach (Match m in SetManifestIdRegex.Matches(content))
        {
            var depotId = m.Groups[1].Value;
            var manifestId = m.Groups[2].Value;
            mappings[depotId] = manifestId;
        }

        return mappings;
    }
}